<?php

namespace Database\Seeders;

use App\Models\TravelLog;
use Illuminate\Database\Seeder;

class TravelLogSeeder extends Seeder
{
    public function run(): void
    {
        TravelLog::truncate();

        $logs = [

            // ── United States (6 hits → darkest blue) ──────────────────────
            [
                'type'           => 'flight',
                'departure_date' => '2024-03-01 09:00:00',
                'arrival_date'   => '2024-03-01 22:00:00',
                'comment'        => 'First trip to New York',
                'place_name'     => 'New York City, New York, United States',
                'city'           => 'New York',
                'country'        => 'United States',
                'latitude'       => 40.7128,
                'longitude'      => -74.0060,
                'from_place_name' => 'London, England, United Kingdom',
                'from_city'       => 'London',
                'from_country'    => 'United Kingdom',
                'from_lat'        => 51.5074,
                'from_lng'        => -0.1278,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2024-03-01 23:00:00',
                'arrival_date'   => '2024-03-05 11:00:00',
                'comment'        => 'Great views of Manhattan',
                'place_name'     => 'New York City, New York, United States',
                'city'           => 'New York',
                'country'        => 'United States',
                'latitude'       => 40.7484,
                'longitude'      => -74.0046,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2024-03-05 14:00:00',
                'arrival_date'   => '2024-03-05 17:30:00',
                'comment'        => 'Cross-country flight to LA',
                'place_name'     => 'Los Angeles, California, United States',
                'city'           => 'Los Angeles',
                'country'        => 'United States',
                'latitude'       => 34.0522,
                'longitude'      => -118.2437,
                'from_place_name' => 'New York City, New York, United States',
                'from_city'       => 'New York',
                'from_country'    => 'United States',
                'from_lat'        => 40.7128,
                'from_lng'        => -74.0060,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2024-03-05 19:00:00',
                'arrival_date'   => '2024-03-08 11:00:00',
                'comment'        => 'Hollywood hills getaway',
                'place_name'     => 'Los Angeles, California, United States',
                'city'           => 'Los Angeles',
                'country'        => 'United States',
                'latitude'       => 34.0967,
                'longitude'      => -118.4614,
            ],
            [
                'type'           => 'car',
                'departure_date' => '2024-03-08 10:00:00',
                'arrival_date'   => '2024-03-08 16:00:00',
                'comment'        => 'Pacific Coast Highway road trip',
                'place_name'     => 'San Francisco, California, United States',
                'city'           => 'San Francisco',
                'country'        => 'United States',
                'latitude'       => 37.7749,
                'longitude'      => -122.4194,
                'from_place_name' => 'Los Angeles, California, United States',
                'from_city'       => 'Los Angeles',
                'from_country'    => 'United States',
                'from_lat'        => 34.0522,
                'from_lng'        => -118.2437,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2025-06-10 08:00:00',
                'arrival_date'   => '2025-06-10 11:00:00',
                'comment'        => 'Business trip to Chicago',
                'place_name'     => 'Chicago, Illinois, United States',
                'city'           => 'Chicago',
                'country'        => 'United States',
                'latitude'       => 41.8781,
                'longitude'      => -87.6298,
                'from_place_name' => 'Miami, Florida, United States',
                'from_city'       => 'Miami',
                'from_country'    => 'United States',
                'from_lat'        => 25.7617,
                'from_lng'        => -80.1918,
            ],

            // ── United Kingdom (4 hits → dark blue) ────────────────────────
            [
                'type'           => 'flight',
                'departure_date' => '2024-01-10 07:30:00',
                'arrival_date'   => '2024-01-10 09:45:00',
                'comment'        => 'Winter trip to London',
                'place_name'     => 'London, England, United Kingdom',
                'city'           => 'London',
                'country'        => 'United Kingdom',
                'latitude'       => 51.5074,
                'longitude'      => -0.1278,
                'from_place_name' => 'Sarajevo, Bosnia and Herzegovina',
                'from_city'       => 'Sarajevo',
                'from_country'    => 'Bosnia and Herzegovina',
                'from_lat'        => 43.8563,
                'from_lng'        => 18.4131,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2024-01-10 15:00:00',
                'arrival_date'   => '2024-01-14 11:00:00',
                'comment'        => 'Stayed near the Thames',
                'place_name'     => 'London, England, United Kingdom',
                'city'           => 'London',
                'country'        => 'United Kingdom',
                'latitude'       => 51.5104,
                'longitude'      => -0.1204,
            ],
            [
                'type'           => 'rail',
                'departure_date' => '2024-09-05 09:00:00',
                'arrival_date'   => '2024-09-05 14:00:00',
                'comment'        => 'Scottish highlands trip',
                'place_name'     => 'Edinburgh, Scotland, United Kingdom',
                'city'           => 'Edinburgh',
                'country'        => 'United Kingdom',
                'latitude'       => 55.9533,
                'longitude'      => -3.1883,
                'from_place_name' => 'London, England, United Kingdom',
                'from_city'       => 'London',
                'from_country'    => 'United Kingdom',
                'from_lat'        => 51.5074,
                'from_lng'        => -0.1278,
            ],

            // ── Australia (3 hits → medium-dark blue) ──────────────────────
            [
                'type'           => 'flight',
                'departure_date' => '2024-11-01 22:00:00',
                'arrival_date'   => '2024-11-02 18:00:00',
                'comment'        => 'Long-haul to Sydney',
                'place_name'     => 'Sydney, New South Wales, Australia',
                'city'           => 'Sydney',
                'country'        => 'Australia',
                'latitude'       => -33.8688,
                'longitude'      => 151.2093,
                'from_place_name' => 'San Francisco, California, United States',
                'from_city'       => 'San Francisco',
                'from_country'    => 'United States',
                'from_lat'        => 37.7749,
                'from_lng'        => -122.4194,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2024-11-03 14:00:00',
                'arrival_date'   => '2024-11-07 10:00:00',
                'comment'        => 'Opera House views, spectacular',
                'place_name'     => 'Sydney, New South Wales, Australia',
                'city'           => 'Sydney',
                'country'        => 'Australia',
                'latitude'       => -33.8568,
                'longitude'      => 151.2153,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2024-11-07 12:00:00',
                'arrival_date'   => '2024-11-07 13:30:00',
                'comment'        => 'Quick hop to Melbourne',
                'place_name'     => 'Melbourne, Victoria, Australia',
                'city'           => 'Melbourne',
                'country'        => 'Australia',
                'latitude'       => -37.8136,
                'longitude'      => 144.9631,
                'from_place_name' => 'Sydney, New South Wales, Australia',
                'from_city'       => 'Sydney',
                'from_country'    => 'Australia',
                'from_lat'        => -33.8688,
                'from_lng'        => 151.2093,
            ],

            // ── France (3 hits → medium-dark blue) ─────────────────────────
            [
                'type'           => 'flight',
                'departure_date' => '2024-01-14 14:00:00',
                'arrival_date'   => '2024-01-14 16:30:00',
                'comment'        => 'Weekend in Paris',
                'place_name'     => 'Paris, Île-de-France, France',
                'city'           => 'Paris',
                'country'        => 'France',
                'latitude'       => 48.8566,
                'longitude'      => 2.3522,
                'from_place_name' => 'London, England, United Kingdom',
                'from_city'       => 'London',
                'from_country'    => 'United Kingdom',
                'from_lat'        => 51.5074,
                'from_lng'        => -0.1278,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2024-01-14 18:00:00',
                'arrival_date'   => '2024-01-17 10:00:00',
                'comment'        => 'Charming hotel in Le Marais district',
                'place_name'     => 'Paris, Île-de-France, France',
                'city'           => 'Paris',
                'country'        => 'France',
                'latitude'       => 48.8566,
                'longitude'      => 2.3522,
            ],
            [
                'type'           => 'rail',
                'departure_date' => '2025-04-10 10:00:00',
                'arrival_date'   => '2025-04-10 13:00:00',
                'comment'        => 'TGV along the French Riviera',
                'place_name'     => 'Marseille, Provence-Alpes-Côte d\'Azur, France',
                'city'           => 'Marseille',
                'country'        => 'France',
                'latitude'       => 43.2965,
                'longitude'      => 5.3698,
                'from_place_name' => 'Lyon, Auvergne-Rhône-Alpes, France',
                'from_city'       => 'Lyon',
                'from_country'    => 'France',
                'from_lat'        => 45.7640,
                'from_lng'        => 4.8357,
            ],

            // ── Brazil (2 hits → medium blue) ───────────────────────────────
            [
                'type'           => 'flight',
                'departure_date' => '2025-01-20 18:00:00',
                'arrival_date'   => '2025-01-21 06:00:00',
                'comment'        => 'Carnival season in São Paulo',
                'place_name'     => 'São Paulo, São Paulo, Brazil',
                'city'           => 'São Paulo',
                'country'        => 'Brazil',
                'latitude'       => -23.5505,
                'longitude'      => -46.6333,
                'from_place_name' => 'Miami, Florida, United States',
                'from_city'       => 'Miami',
                'from_country'    => 'United States',
                'from_lat'        => 25.7617,
                'from_lng'        => -80.1918,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2025-01-21 09:00:00',
                'arrival_date'   => '2025-01-25 11:00:00',
                'comment'        => 'Vibrant city, incredible food',
                'place_name'     => 'São Paulo, São Paulo, Brazil',
                'city'           => 'São Paulo',
                'country'        => 'Brazil',
                'latitude'       => -23.5629,
                'longitude'      => -46.6544,
            ],

            // ── Single-visit countries (light blue) ─────────────────────────
            [
                'type'           => 'rail',
                'departure_date' => '2024-01-17 11:00:00',
                'arrival_date'   => '2024-01-17 14:20:00',
                'comment'        => 'TGV to Milan',
                'place_name'     => 'Milan, Lombardy, Italy',
                'city'           => 'Milan',
                'country'        => 'Italy',
                'latitude'       => 45.4654,
                'longitude'      => 9.1859,
                'from_place_name' => 'Paris, Île-de-France, France',
                'from_city'       => 'Paris',
                'from_country'    => 'France',
                'from_lat'        => 48.8566,
                'from_lng'        => 2.3522,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2024-06-15 07:00:00',
                'arrival_date'   => '2024-06-15 14:00:00',
                'comment'        => 'Dream trip to Tokyo',
                'place_name'     => 'Tokyo, Japan',
                'city'           => 'Tokyo',
                'country'        => 'Japan',
                'latitude'       => 35.6762,
                'longitude'      => 139.6503,
                'from_place_name' => 'London, England, United Kingdom',
                'from_city'       => 'London',
                'from_country'    => 'United Kingdom',
                'from_lat'        => 51.5074,
                'from_lng'        => -0.1278,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2024-06-15 17:00:00',
                'arrival_date'   => '2024-06-21 10:00:00',
                'comment'        => 'Lost in Translation vibes',
                'place_name'     => 'Tokyo, Japan',
                'city'           => 'Tokyo',
                'country'        => 'Japan',
                'latitude'       => 35.6879,
                'longitude'      => 139.6917,
            ],
            [
                'type'           => 'car',
                'departure_date' => '2025-03-05 09:00:00',
                'arrival_date'   => '2025-03-05 13:00:00',
                'comment'        => 'Road trip through Bavaria',
                'place_name'     => 'Berlin, Germany',
                'city'           => 'Berlin',
                'country'        => 'Germany',
                'latitude'       => 52.5200,
                'longitude'      => 13.4050,
                'from_place_name' => 'Munich, Bavaria, Germany',
                'from_city'       => 'Munich',
                'from_country'    => 'Germany',
                'from_lat'        => 48.1351,
                'from_lng'        => 11.5820,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2025-05-20 06:45:00',
                'arrival_date'   => '2025-05-20 11:00:00',
                'comment'        => 'Adriatic summer escape',
                'place_name'     => 'Dubrovnik, Dubrovnik-Neretva County, Croatia',
                'city'           => 'Dubrovnik',
                'country'        => 'Croatia',
                'latitude'       => 42.6507,
                'longitude'      => 18.0944,
                'from_place_name' => 'Barcelona, Catalonia, Spain',
                'from_city'       => 'Barcelona',
                'from_country'    => 'Spain',
                'from_lat'        => 41.3851,
                'from_lng'        => 2.1734,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2025-07-12 11:00:00',
                'arrival_date'   => '2025-07-12 20:00:00',
                'comment'        => 'Summer holiday in Mexico City',
                'place_name'     => 'Mexico City, Mexico',
                'city'           => 'Mexico City',
                'country'        => 'Mexico',
                'latitude'       => 19.4326,
                'longitude'      => -99.1332,
                'from_place_name' => 'Chicago, Illinois, United States',
                'from_city'       => 'Chicago',
                'from_country'    => 'United States',
                'from_lat'        => 41.8781,
                'from_lng'        => -87.6298,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2025-08-20 08:00:00',
                'arrival_date'   => '2025-08-20 12:30:00',
                'comment'        => 'Safari and Cape Town adventure',
                'place_name'     => 'Cape Town, Western Cape, South Africa',
                'city'           => 'Cape Town',
                'country'        => 'South Africa',
                'latitude'       => -33.9249,
                'longitude'      => 18.4241,
                'from_place_name' => 'Johannesburg, Gauteng, South Africa',
                'from_city'       => 'Johannesburg',
                'from_country'    => 'South Africa',
                'from_lat'        => -26.2041,
                'from_lng'        => 28.0473,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2025-09-10 07:00:00',
                'arrival_date'   => '2025-09-10 10:30:00',
                'comment'        => 'Back home',
                'place_name'     => 'Sarajevo, Bosnia and Herzegovina',
                'city'           => 'Sarajevo',
                'country'        => 'Bosnia and Herzegovina',
                'latitude'       => 43.8563,
                'longitude'      => 18.4131,
                'from_place_name' => 'Prague, Bohemia, Czech Republic',
                'from_city'       => 'Prague',
                'from_country'    => 'Czech Republic',
                'from_lat'        => 50.0755,
                'from_lng'        => 14.4378,
            ],
        ];

        foreach ($logs as $log) {
            TravelLog::create($log);
        }

        $this->command->info('🌱 Demo travel logs seeded (' . count($logs) . ' entries)');
    }
}

