<?php

namespace Database\Seeders;

use App\Models\TravelLog;
use Illuminate\Database\Seeder;

class TravelLogSeeder extends Seeder
{
    public function run(): void
    {
        TravelLog::truncate();

        $logs = [
            // --- Flights ---
            [
                'type'           => 'flight',
                'departure_date' => '2025-01-10 07:30:00',
                'arrival_date'   => '2025-01-10 09:45:00',
                'departure_place' => 'Sarajevo International Airport',
                'arrival_place'   => 'London Heathrow Airport',
                'comment'        => 'Winter trip to London',
                // Destination
                'place_name' => 'London, England, United Kingdom',
                'city'       => 'London',
                'country'    => 'United Kingdom',
                'latitude'   => 51.5074,
                'longitude'  => -0.1278,
                // Origin
                'from_place_name' => 'Sarajevo, Bosnia and Herzegovina',
                'from_city'       => 'Sarajevo',
                'from_country'    => 'Bosnia and Herzegovina',
                'from_lat'        => 43.8563,
                'from_lng'        => 18.4131,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2025-01-10 15:00:00',
                'arrival_date'   => '2025-01-13 11:00:00',
                'accommodation_place' => 'The Savoy, London',
                'comment'        => 'Stayed near the Thames',
                'place_name' => 'London, England, United Kingdom',
                'city'       => 'London',
                'country'    => 'United Kingdom',
                'latitude'   => 51.5104,
                'longitude'  => -0.1204,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2025-01-13 14:00:00',
                'arrival_date'   => '2025-01-13 16:30:00',
                'departure_place' => 'London Heathrow Airport',
                'arrival_place'   => 'Charles de Gaulle Airport',
                'comment'        => 'Quick hop to Paris',
                'place_name' => 'Paris, Île-de-France, France',
                'city'       => 'Paris',
                'country'    => 'France',
                'latitude'   => 48.8566,
                'longitude'  => 2.3522,
                'from_place_name' => 'London, England, United Kingdom',
                'from_city'       => 'London',
                'from_country'    => 'United Kingdom',
                'from_lat'        => 51.5074,
                'from_lng'        => -0.1278,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2025-01-13 18:00:00',
                'arrival_date'   => '2025-01-16 10:00:00',
                'accommodation_place' => 'Hôtel Le Marais, Paris',
                'comment'        => 'Charming hotel in Le Marais district',
                'place_name' => 'Paris, Île-de-France, France',
                'city'       => 'Paris',
                'country'    => 'France',
                'latitude'   => 48.8566,
                'longitude'  => 2.3522,
            ],
            [
                'type'           => 'rail',
                'departure_date' => '2025-01-16 11:00:00',
                'arrival_date'   => '2025-01-16 14:20:00',
                'departure_place' => 'Paris Gare de Lyon',
                'arrival_place'   => 'Milan Centrale',
                'comment'        => 'TGV to Milan',
                'place_name' => 'Milan, Lombardy, Italy',
                'city'       => 'Milan',
                'country'    => 'Italy',
                'latitude'   => 45.4654,
                'longitude'  => 9.1859,
                'from_place_name' => 'Paris, Île-de-France, France',
                'from_city'       => 'Paris',
                'from_country'    => 'France',
                'from_lat'        => 48.8566,
                'from_lng'        => 2.3522,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2025-01-16 15:00:00',
                'arrival_date'   => '2025-01-18 11:00:00',
                'accommodation_place' => 'Hotel Brera, Milan',
                'comment'        => 'Design district stay',
                'place_name' => 'Milan, Lombardy, Italy',
                'city'       => 'Milan',
                'country'    => 'Italy',
                'latitude'   => 45.4723,
                'longitude'  => 9.1815,
            ],
            [
                'type'           => 'car',
                'departure_date' => '2025-03-05 09:00:00',
                'arrival_date'   => '2025-03-05 13:00:00',
                'departure_place' => 'Munich',
                'arrival_place'   => 'Berlin',
                'comment'        => 'Road trip through Bavaria',
                'place_name' => 'Berlin, Germany',
                'city'       => 'Berlin',
                'country'    => 'Germany',
                'latitude'   => 52.5200,
                'longitude'  => 13.4050,
                'from_place_name' => 'Munich, Bavaria, Germany',
                'from_city'       => 'Munich',
                'from_country'    => 'Germany',
                'from_lat'        => 48.1351,
                'from_lng'        => 11.5820,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2025-03-08 10:00:00',
                'arrival_date'   => '2025-03-08 13:15:00',
                'departure_place' => 'Berlin Brandenburg Airport',
                'arrival_place'   => 'Barcelona El Prat Airport',
                'comment'        => 'Spring trip to Barcelona',
                'place_name' => 'Barcelona, Catalonia, Spain',
                'city'       => 'Barcelona',
                'country'    => 'Spain',
                'latitude'   => 41.3851,
                'longitude'  => 2.1734,
                'from_place_name' => 'Berlin, Germany',
                'from_city'       => 'Berlin',
                'from_country'    => 'Germany',
                'from_lat'        => 52.5200,
                'from_lng'        => 13.4050,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2025-03-08 15:00:00',
                'arrival_date'   => '2025-03-11 10:00:00',
                'accommodation_place' => 'Hotel Arts Barcelona',
                'comment'        => 'Beach-front hotel, great views',
                'place_name' => 'Barcelona, Catalonia, Spain',
                'city'       => 'Barcelona',
                'country'    => 'Spain',
                'latitude'   => 41.3874,
                'longitude'  => 2.1965,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2025-05-20 06:45:00',
                'arrival_date'   => '2025-05-20 11:00:00',
                'departure_place' => 'Barcelona El Prat Airport',
                'arrival_place'   => 'Dubrovnik Airport',
                'comment'        => 'Adriatic summer escape',
                'place_name' => 'Dubrovnik, Dubrovnik-Neretva County, Croatia',
                'city'       => 'Dubrovnik',
                'country'    => 'Croatia',
                'latitude'   => 42.6507,
                'longitude'  => 18.0944,
                'from_place_name' => 'Barcelona, Catalonia, Spain',
                'from_city'       => 'Barcelona',
                'from_country'    => 'Spain',
                'from_lat'        => 41.3851,
                'from_lng'        => 2.1734,
            ],
            [
                'type'           => 'hotel',
                'departure_date' => '2025-05-20 14:00:00',
                'arrival_date'   => '2025-05-24 10:00:00',
                'accommodation_place' => 'Villa Dubrovnik',
                'comment'        => 'Old town views, amazing sunsets',
                'place_name' => 'Dubrovnik, Dubrovnik-Neretva County, Croatia',
                'city'       => 'Dubrovnik',
                'country'    => 'Croatia',
                'latitude'   => 42.6405,
                'longitude'  => 18.1083,
            ],
            [
                'type'           => 'rail',
                'departure_date' => '2025-07-14 08:00:00',
                'arrival_date'   => '2025-07-14 11:45:00',
                'departure_place' => 'Amsterdam Centraal',
                'arrival_place'   => 'Brussels Midi',
                'comment'        => 'Intercity rail through the Low Countries',
                'place_name' => 'Brussels, Brussels-Capital Region, Belgium',
                'city'       => 'Brussels',
                'country'    => 'Belgium',
                'latitude'   => 50.8503,
                'longitude'  => 4.3517,
                'from_place_name' => 'Amsterdam, North Holland, Netherlands',
                'from_city'       => 'Amsterdam',
                'from_country'    => 'Netherlands',
                'from_lat'        => 52.3676,
                'from_lng'        => 4.9041,
            ],
            [
                'type'           => 'car',
                'departure_date' => '2025-08-01 10:00:00',
                'arrival_date'   => '2025-08-01 16:00:00',
                'departure_place' => 'Vienna',
                'arrival_place'   => 'Prague',
                'comment'        => 'Central Europe road trip',
                'place_name' => 'Prague, Bohemia, Czech Republic',
                'city'       => 'Prague',
                'country'    => 'Czech Republic',
                'latitude'   => 50.0755,
                'longitude'  => 14.4378,
                'from_place_name' => 'Vienna, Austria',
                'from_city'       => 'Vienna',
                'from_country'    => 'Austria',
                'from_lat'        => 48.2082,
                'from_lng'        => 16.3738,
            ],
            [
                'type'           => 'flight',
                'departure_date' => '2025-09-10 07:00:00',
                'arrival_date'   => '2025-09-10 10:30:00',
                'departure_place' => 'Prague Václav Havel Airport',
                'arrival_place'   => 'Sarajevo International Airport',
                'comment'        => 'Back home after summer travels',
                'place_name' => 'Sarajevo, Bosnia and Herzegovina',
                'city'       => 'Sarajevo',
                'country'    => 'Bosnia and Herzegovina',
                'latitude'   => 43.8563,
                'longitude'  => 18.4131,
                'from_place_name' => 'Prague, Bohemia, Czech Republic',
                'from_city'       => 'Prague',
                'from_country'    => 'Czech Republic',
                'from_lat'        => 50.0755,
                'from_lng'        => 14.4378,
            ],
        ];

        foreach ($logs as $log) {
            TravelLog::create($log);
        }

        $this->command->info('🌱 Demo travel logs seeded (' . count($logs) . ' entries)');
    }
}

